presets:
  always_on:
    default:
      collect: true
      analyze: false
      push: true
      report_mode: "current"
      ai_mode: "follow_report"
      once:
        analyze: false
        push: false
    periods: {}
    day_plans:
      all_day:
        periods: []
    week_map:
      1: "all_day"
      2: "all_day"
      3: "all_day"
      4: "all_day"
      5: "all_day"
      6: "all_day"
      7: "all_day"

custom:
  default:
    collect: true
    analyze: false
    push: true
    report_mode: "current"
    ai_mode: "follow_report"
    once:
      analyze: false
      push: false
  periods: {}
  day_plans:
    all_day:
      periods: []
  week_map:
    1: "all_day"
    2: "all_day"
    3: "all_day"
    4: "all_day"
    5: "all_day"
    6: "all_day"
    7: "all_day"
